# Drawing on:
# https://pre-commit.ci/
# https://pre-commit.com/#usage
# https://github.com/pdm-project/pdm/blob/main/.pre-commit-config.yaml
# https://github.com/nonebot/nonebot2/blob/master/.pre-commit-config.yaml

ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: "Auto fix by pre-commit hooks"
  autoupdate_commit_msg: "Auto update by pre-commit hooks"

repos:
  # upgrade the syntax.
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade

  # adding "from __future__ import annotations" for enabling new features
  - repo: https://github.com/frostming/fix-future-annotations
    rev: 0.5.0
    hooks:
      - id: fix-future-annotations

  # code style formatting
  # see pyproject.toml for config
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  # removing unused import statements
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln

  # import sentences sorting
  # see pyproject.toml for config
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  # typo checking
  # see setup.cfg for config
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell

  # common python problem checking
  # see setup.cfg for config
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear


  # see setup.cfg for config
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        args: [ puntgun ]
        pass_filenames: false
        additional_dependencies:
          - types-requests
          - types-certifi