[tool.poetry]
name = "puntgun"
version = "0.1.0"
description = "A configurable automation command line tool for Twitter."
authors = ["boholder <bottleholder@anche.no>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
dynaconf = "^3.1.9"
tweepy = "^4.10.0"
reactivex = "^4.0.4"
fire = "^0.4.0"
from-root = "^1.0.2"
cryptography = "^37.0.4"
loguru = "^0.6.0"
pydantic = "^1.9.1"
orjson = "^3.7.11"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
PyHamcrest = "^2.0.3"

[tool.pytest.ini_options]
pythonpath = ["puntgun", "tests"]

[tool.coverage.run]
relative_files = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
