# The settings of the tool itself.
# Can be overridden by the same-name ones in the user-writen plan configuration file
# or in the environment variables.

name: bob

users:
  # user source rule
  from:
    # '@Alice', '@Bob' and '@Charlie'
    - names: [ 'Alice', 'Bob', 'Charlie' ]
  # user filter rule
  that:
    - follower:
        less_than: 10
  # user action rule
  do:
    - block