# The settings of the tool itself.
# Can be overridden by the same-name ones in the user-writen plan configuration file
# or in the environment variables.
# The values of the commented out options are default values
# Reference document: TODO

# Whether to block users that you're following.
#block_following: false

# Whether to block users that following you.
#block_follower: true

# Change log files writing method (when to split a new file)
#log_rotation: 100MB