from puntgun.model.user import User


class Exchange(object):
    """
    DTO, generated by :class:`UserSelectingRule` and may be modified between rules.
    The set of information passed between rules
    and is used as the input value (i.e., the object) of the rule judgment logic.
    One instance represent one potential user's information.
    """

    def __init__(self, user: User):
        self.user_id = user.id
        self.user = user
