# Your can refer https://yaml.org/ for the syntax of the YAML.
# For character escaping content, read this:
# https://pyyaml.org/wiki/PyYAMLDocumentation#scalars
#
# For possible configuration options, see option-manual.md in the root directory,
# or check the latest version of online manual:
# https://github.com/boholder/puntgun/blob/main/config-manual.md

# ========================
# script behavior settings
# ========================

manually_confirm: false

# ========================
# rules
# ========================

block:
  - users:
      who:
        id_are: [ "12345678", "87654321" ]

  - users:
      who:
        username_are: [ "Twitter", "TwitterAPI" ]

  - users:
      who:
        are_my_follower:
          recent: 100

  - users:
      who:
        hit_search_results_of:
          - search:
              name: hate coffee or cats
              query: '"hate" "coffee" OR "cats"'
              count: 100
          - search_query: '"收留无家可归的乌克兰小姐姐"'
          - search_query: '"son of a b*tch"'

  - users:
      who:
        agree_with_tweet:
          id: "12345678"
          search_query: 'text_text_text'

  - users:
      who:
        id_are: [ "12345678", "87654321" ]
      any_of:
        - search_query: 'text_text_text'
        - all_of:
            - user_created:
                after: "2019-01-01 00:00:00"
                before: "2020-01-01"
            - user_texts_match: '[\u1F100-\u1F1E5]'
            - user_follower:
                more_than: 1
                less_than: 1000
            - user_following:
                more_than: 1
                less_than: 1000
            # follower / following
            - user_foer_foing_ratio:
                more_than: 0.1 # 1 follower / 10 following
                less_than: 3 # 3 follower / 1 following
            - user_tweet_count:
                more_than: 1
                less_than: 100
            - user_recent_speaking_ratio:
                recent: 100
                more_than: 0.05 # 5 post / 95 retweet in 100 tweets
                less_than: 0.9 # 90 post / 10 retweet in 100 tweets

        - let_me_check:
            user_info: ture
            recent_tweets: 3
            recent_replies:
              count: 3
              with_origin_tweet: true
            recent_likes: 3

fragments:
  - search_rules:
      - search_query: 'tweet_query_string-1'
      - search_query: 'tweet_query_string-2'

  - numeric_fields:
      more_than: 10
      less_than: 1000