# Action on main branch to run unit tests and update coverage info to https://coveralls.io

name: CI-MAIN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-unit-test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install pdm
          pdm install
          pdm add setuptools pip wheel "coverage[toml]"

      - name: Run coverage
        run: pdm run coverage run -m pytest tests

      - name: Coveralls
        # https://github.com/AndreMiras/coveralls-python-action/pull/16#issuecomment-1003445652
        # so I forked this repo and merged this PR in my fork
        # https://github.com/boholder/coveralls-python-action/
        uses: boholder/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: GitHub Action CI-MAIN

  coveralls_finish:
    needs: run-unit-test-suite
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: boholder/coveralls-python-action@develop
        with:
          parallel-finished: true