# This is a basic workflow to help you get started with Actions

name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  paste-coverage-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install poetry
          poetry install

      - name: Run coverage
        run: |
          coverage run -m pytest tests
          coverage xml --data-file=.coverage -o coverage.xml

      - name: Python Cov
        uses: orgoro/coverage@v2.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}