# Action to run unit tests and update coverage info to https://coveralls.io
# Take example by:
# https://github.com/pypa/pipx/blob/main/.github/workflows/tests.yml


name: TEST

on:
  push:
  pull_request:

jobs:
  run-unit-test-suite:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]
        python-version: [ "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pdm
          pdm install
          pdm add setuptools pip wheel "coverage[toml]"

      - name: Run coverage
        run: pdm run coverage run -m pytest tests

      - name: Coveralls
        # https://github.com/AndreMiras/coveralls-python-action/pull/16#issuecomment-1003445652
        # so I forked this repo and merged this PR in my fork
        # https://github.com/boholder/coveralls-python-action/
        uses: boholder/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: GitHub Action CI-MAIN

  coveralls_finish:
    needs: run-unit-test-suite
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: boholder/coveralls-python-action@develop
        with:
          parallel-finished: true