# Workflow to run unit tests and update coverage info to https://coveralls.io
# Drawing on:
# https://github.com/pypa/pipx/blob/main/.github/workflows/tests.yml


name: Test

on: [ push, pull_request ]

env:
  default-python: "3.10"

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.default-python }}

      - name: Install lint dependencies
        run: |
          python3 -m pip install -U pdm
          pdm install -dG lint

      - name: Run lint check
        run: pdm run lint

  test-on-win-mac:
    needs: lint-check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.default-python }}

      - name: Install test dependencies
        run: |
          python3 -m pip install -U pdm
          pdm install -G test

      - name: Run pytest
        run: pdm run python -m pytest tests


  test-and-gen-coverage-on-linux:
    needs: lint-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.default-python }}

      - name: Install test dependencies
        run: |
          python3 -m pip install -U pdm
          pdm install -G test

      - name: Run coverage
        run: pdm run coverage

      - name: Run Coveralls
        # https://github.com/AndreMiras/coveralls-python-action/pull/16#issuecomment-1003445652
        # so I forked this repo and merged this PR in my fork
        # https://github.com/boholder/coveralls-python-action/
        uses: boholder/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: GitHub Action TEST

  upload-coverage-to-coveralls:
    needs: test-and-gen-coverage-on-linux
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: boholder/coveralls-python-action@develop
        with:
          parallel-finished: true